 server:
  servlet-path: "*.action"
  port: 8090
 spring:
  mvc:
   view.prefix: /static/view/
   view.suffix: .jsp 
  datasource:
   url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
   username: scott
   password: Xiang0416    
   driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
   database: 13
   host: 127.0.0.1
   port: 6379
   password:
   pool:
    max-wait: -1
    max-idle: 10
    min-idle: 0
   timeout: 1000 
    
   
 mybatis:
  mapper-locations: classpath:/mapper/empMapper.xml
  
           